import { Navigation } from "@/components/navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <Navigation />
      <main className="py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white mb-6">Legal Information</h1>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Important legal notices and disclaimers for QuizGen users
            </p>
          </div>

          <div className="space-y-8">
            <Card className="border-0 shadow-lg bg-white dark:bg-gray-800">
              <CardHeader>
                <CardTitle className="text-2xl text-gray-900 dark:text-white">Terms of Service</CardTitle>
              </CardHeader>
              <CardContent className="prose prose-gray dark:prose-invert max-w-none">
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                  By using QuizGen, you agree to these terms of service. Our platform is provided "as is" for
                  educational purposes. Users are responsible for ensuring their uploaded content complies with
                  applicable laws and regulations.
                </p>
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mt-6 mb-3">Acceptable Use</h4>
                <ul className="text-gray-600 dark:text-gray-300 space-y-2">
                  <li>Use the service only for legitimate educational purposes</li>
                  <li>Do not upload copyrighted material without permission</li>
                  <li>Respect intellectual property rights of others</li>
                  <li>Do not attempt to reverse engineer or exploit the service</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg bg-white dark:bg-gray-800">
              <CardHeader>
                <CardTitle className="text-2xl text-gray-900 dark:text-white">Privacy Policy</CardTitle>
              </CardHeader>
              <CardContent className="prose prose-gray dark:prose-invert max-w-none">
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                  We take your privacy seriously. This section outlines how we collect, use, and protect your
                  information.
                </p>
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mt-6 mb-3">Data Collection</h4>
                <ul className="text-gray-600 dark:text-gray-300 space-y-2">
                  <li>We temporarily process uploaded files to generate quizzes</li>
                  <li>Files are automatically deleted after processing</li>
                  <li>We do not store personal information without consent</li>
                  <li>Usage analytics are collected anonymously</li>
                </ul>
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mt-6 mb-3">Data Security</h4>
                <p className="text-gray-600 dark:text-gray-300">
                  All data transmission is encrypted using industry-standard protocols. Our servers are secured and
                  regularly updated.
                </p>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg bg-white dark:bg-gray-800">
              <CardHeader>
                <CardTitle className="text-2xl text-gray-900 dark:text-white">AI and Content Disclaimer</CardTitle>
              </CardHeader>
              <CardContent className="prose prose-gray dark:prose-invert max-w-none">
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                  QuizGen uses artificial intelligence to generate quiz content. Please be aware of the following:
                </p>
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mt-6 mb-3">AI-Generated Content</h4>
                <ul className="text-gray-600 dark:text-gray-300 space-y-2">
                  <li>Quiz questions are generated by Google's Gemini AI model</li>
                  <li>Content accuracy should be verified by educators</li>
                  <li>AI may occasionally produce incorrect or biased information</li>
                  <li>Generated content should be reviewed before use in formal assessments</li>
                </ul>
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mt-6 mb-3">Educational Use</h4>
                <p className="text-gray-600 dark:text-gray-300">
                  This tool is designed to assist educators and should not replace human judgment in educational
                  assessment. Always review generated content for accuracy and appropriateness.
                </p>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg bg-white dark:bg-gray-800">
              <CardHeader>
                <CardTitle className="text-2xl text-gray-900 dark:text-white">Limitation of Liability</CardTitle>
              </CardHeader>
              <CardContent className="prose prose-gray dark:prose-invert max-w-none">
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                  QuizGen is provided for educational purposes only. We make no warranties about the accuracy,
                  completeness, or suitability of generated content for any particular purpose.
                </p>
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mt-6 mb-3">Disclaimers</h4>
                <ul className="text-gray-600 dark:text-gray-300 space-y-2">
                  <li>Service is provided "as is" without warranties</li>
                  <li>We are not liable for any educational or assessment outcomes</li>
                  <li>Users assume full responsibility for content verification</li>
                  <li>Service availability is not guaranteed</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg bg-white dark:bg-gray-800">
              <CardHeader>
                <CardTitle className="text-2xl text-gray-900 dark:text-white">Contact Information</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
                  If you have questions about these legal terms or need to report an issue, please contact us:
                </p>
                <div className="space-y-2 text-gray-600 dark:text-gray-300">
                  <p>
                    <strong>Email:</strong> legal@quizgen.ai
                  </p>
                  <p>
                    <strong>Address:</strong> 123 Education Street, San Francisco, CA 94105
                  </p>
                  <p>
                    <strong>Last Updated:</strong> January 2025
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}